# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
game_versions=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=4.2+26.1
maven_group=niv.heater
archives_base_name=heater
project_id=g3jBz897

# Dependencies
fabric_api_version=0.145.1+26.1
burning_version=3.0+26.1
